---
title: "14_AGF- Survival stats figure"
author: "Alex Macadam"
date: "2023-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Survival statistics
```{r}
library(tidyverse) #for data wrangling
library(car)       #for regression diagnostics
library(broom)     #for tidy output
library(ggfortify) #for model diagnostics
library(sjPlot)    #for outputs
library(knitr)     #for kable
library(effects)   #for partial effects plots
library(emmeans)   #for estimating marginal means
library(MASS)      #for glm.nb
library(MuMIn)     #for AICc
library(brms)
library(broom.mixed)
library(tidybayes)
library(bayesplot)
#library(standist)   #for visualizing distributions
library(rstanarm)
library(ggeffects)
library(rstan)
library(DHARMa)
library(ggridges)
library(easystats)     #framework for stats, modelling and visualisation
library(patchwork)
library(car)       #for regression diagnostics
library(broom)     #for tidy output
library(broom.mixed)
library(ggfortify) #for model diagnostics
#library(sjPlot)    #for outputs
library(knitr)     #for kable
source('C:/Users/amacadam/Dropbox/PhD/Chapter 5- Outplanting/Chapter 5 Scripts/Chapter-5--Outplanting-AGF-corals/helperFunctions.R')
```

```{r}
survival.brm2_A.tenuis_larv<- readRDS("survival.brm2_A.tenuis_larv.rds")
survival.brm3_A.hyacinthus<- readRDS("survival.brm3_A.hyacinthus.rds")
survival.brm2_G.retiformis<- readRDS("survival.brm2_G.retiformis.rds")
survival.brm2_A.tenuis_juv<- readRDS("survival.brm2_A.tenuis_juv.rds")
survival.brm2_A.hyacinthus_juv<- readRDS("survival.brm2_A.hyacinthus_juv.rds")
survival.brm4_A.hyacinthus_juv<- readRDS("survival.brm4_A.hyacinthus_juv.rds")
```

```{r}
survival.brm2_A.tenuis_larv_plot<- survival.brm2_A.tenuis_larv %>%
  emmeans(~popcross) %>%
  gather_emmeans_draws() %>%
    ggplot() +
  #geom_vline(xintercept = 0, linetype = "dashed") +
  stat_slab(aes(
    x = .value, y = popcross,
    fill = stat(ggdist::cut_cdf_qi(cdf,
      .width = c(0.5, 0.8, 0.95),
      labels = scales::percent_format()
    ))
  ), color = "black") +
  scale_fill_brewer("Interval", direction = -1, na.translate = FALSE) +
  theme_classic()+
  labs(x = "Survival", y = "Reef Cross")
survival.brm2_A.tenuis_larv_plot
```

```{r}
survival.brm3_A.hyacinthus_plot<- survival.brm3_A.hyacinthus %>%
  emmeans(~popcross) %>%
  gather_emmeans_draws() %>%
    ggplot() +
  #geom_vline(xintercept = 0, linetype = "dashed") +
  stat_slab(aes(
    x = .value, y = popcross,
    fill = stat(ggdist::cut_cdf_qi(cdf,
      .width = c(0.5, 0.8, 0.95),
      labels = scales::percent_format()
    ))
  ), color = "black") +
  scale_fill_brewer("Interval", direction = -1, na.translate = FALSE) +
  theme_classic()+
  labs(x = "Survival", y = "Reef Cross")
survival.brm3_A.hyacinthus_plot
```

```{r}
survival.brm2_G.retiformis_plot<- survival.brm2_G.retiformis %>%
  emmeans(~popcross) %>%
  gather_emmeans_draws() %>%
    ggplot() +
  #geom_vline(xintercept = 0, linetype = "dashed") +
  stat_slab(aes(
    x = .value, y = popcross,
    fill = stat(ggdist::cut_cdf_qi(cdf,
      .width = c(0.5, 0.8, 0.95),
      labels = scales::percent_format()
    ))
  ), color = "black") +
  scale_fill_brewer("Interval", direction = -1, na.translate = FALSE) +
  theme_classic()+
  labs(x = "Survival", y = "Reef Cross")
survival.brm2_G.retiformis_plot
```

```{r}
survival.brm2_A.tenuis_juv_plot<- survival.brm2_A.tenuis_juv %>%
  emmeans(~popcross) %>%
  gather_emmeans_draws() %>%
    ggplot() +
  #geom_vline(xintercept = 0, linetype = "dashed") +
  stat_slab(aes(
    x = .value, y = popcross,
    fill = stat(ggdist::cut_cdf_qi(cdf,
      .width = c(0.5, 0.8, 0.95),
      labels = scales::percent_format()
    ))
  ), color = "black") +
  scale_fill_brewer("Interval", direction = -1, na.translate = FALSE) +
  theme_classic()+
  labs(x = "Survival", y = "Reef Cross")
survival.brm2_A.tenuis_juv_plot
```

```{r}
survival.brm2_A.hyacinthus_juv_plot<- survival.brm2_A.hyacinthus_juv %>%
  emmeans(~popcross) %>%
  gather_emmeans_draws() %>%
    ggplot() +
  #geom_vline(xintercept = 0, linetype = "dashed") +
  stat_slab(aes(
    x = .value, y = popcross,
    fill = stat(ggdist::cut_cdf_qi(cdf,
      .width = c(0.5, 0.8, 0.95),
      labels = scales::percent_format()
    ))
  ), color = "black") +
  scale_fill_brewer("Interval", direction = -1, na.translate = FALSE) +
  theme_classic()+
  labs(x = "Survival", y = "Reef Cross")
survival.brm2_A.hyacinthus_juv_plot
```

```{r}
(survival.brm2_A.tenuis_larv_plot + survival.brm3_A.hyacinthus_plot + survival.brm2_G.retiformis_plot) /
(survival.brm2_A.tenuis_juv_plot + survival.brm2_A.hyacinthus_juv_plot) + plot_annotation(tag_levels = 'A') + plot_layout(guides = 'collect', ncol = 3)

survival.brm2_A.tenuis_larv_plot + survival.brm3_A.hyacinthus_plot + survival.brm2_G.retiformis_plot + survival.brm2_A.tenuis_juv_plot + survival.brm2_A.hyacinthus_juv_plot + plot_annotation(tag_levels = 'A') + plot_layout(guides = 'collect', nrow = 3)
```

```{r}
#ggsave('C:/Users/amacadam/Dropbox/PhD/Chapter 2- Physiology/Chapter 2 figures/Draft figures/Draft 7/Sup_Fig3_Juv_Final_Phys.pdf', fig4.3,
 #     device="pdf", width=10, height=10, units = "in")
```

